- Gemfile
- Gemfile.lock
- app/policies/application_policy.rb
- Added the gem to the gem file
- I ran pundit:install ( It generated the policy folder)
After pulling don't forget to bundle install
> generated the pundit:installation

- app/models/activity.rb
- db/migrate/20221206183613_create_activities.rb
- db/schema.rb
- test/models/activity_test.rb
- Created the activity model
don't forget to db:create, db:migrate
> create the activities model

- app/models/activity.rb
- app/models/activity_question.rb
- app/models/badge.rb
- app/models/teacher_comment.rb
- app/models/user.rb
- app/models/user_response.rb
- db/migrate/20221206214251_create_activity_questions.rb
- db/migrate/20221206214752_create_badges.rb
- db/migrate/20221206215145_create_user_responses.rb
- db/migrate/20221206215858_create_teacher_comments.rb
- db/schema.rb
- test/models/activity_question_test.rb
- test/models/badge_test.rb
- test/models/teacher_comment_test.rb
- test/models/user_response_test.rb
Created tables/models: 
- badges
- activity_questions
- user_responses
- teacher_comments
Plus their associations
> Created activity-related tables/models and their associations

- db/migrate/20221206232043_add_fields_to_users_table.rb
- db/schema.rb
- Added first name to users table
- Added last name to users table
- Added user name to users table
-  Added teacher boolean to users table
> added the missing fields to users table

- package-lock.json
- yarn.lock
Getting error:  `Can't find the 'libpq-fe.h header` when pushing to production
Attempting to solve using: 
`brew install postgresql`
`gem install pg`
> ran <brew install postgresql> + <gem install pg>

- app/policies/activity_policy.rb
- app/policies/activity_question_policy.rb
- app/policies/teacher_comment_policy.rb
- app/policies/user_response_policy.rb
- test/policies/activity_policy_test.rb
- test/policies/activity_question_policy_test.rb
- test/policies/teacher_comment_policy_test.rb
- test/policies/user_response_policy_test.rb
- Created pundit policy for activity
- Created pundit policy for activity_activity
- Created pundit policy for teacher_comment
- Created pundit policy for user_response
> generated punditnpolicies

- Gemfile
- Gemfile.lock
- app/controllers/pages_controller.rb
- app/views/pages/play.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- yarn.lock
- Created the routes
- Created the action in pages controller
- Created the view.html.erb
- Added a link to the navbar
> Create play page

- app/models/activity.rb
- app/models/activity_question.rb
- app/models/user.rb
- db/migrate/20221206232043_add_fields_to_users_table.rb
- db/migrate/20221208185327_remove_type_from_activity.rb
- db/schema.rb
- db/seeds.rb
- Created instances of all models for the seed.
- In the migration for User, made a minor correction, changed a symbol to a boolean
- Added validations to activity and activity question
To test:
Run the seed and verify everything was created in the database
We will still need to add destroy dependencies to some models.
> Filled in the seed, added validations to models, minor fixes

- app/controllers/pages_controller.rb
- app/views/pages/home.html.erb
- Defined students in the pages_controller's "home" action
- Displayed students on home page, text changes depending on whether user signed in is a teacher or a student.
> Home page visit

- Gemfile.lock
- app/controllers/activities_controller.rb
- app/controllers/application_controller.rb
- app/policies/activity_policy.rb
- app/views/activities/index.html.erb
- Created a view folder for activities (may create a conflict)
- Added the policy for the index action
- Made a simple view page for activities index
- Edited the application controller to add missing policy code from Le Wagon lecture page'
Test:
- Check the view page for the index to make sure it appears properly. The links to each activity will be dead until Reems show page branch is merged. Make sure that only logged in users can see the activities page.
> Created the index action for activities, added the policy as well.

- app/controllers/activities_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/user_responses_controller.rb
- app/policies/activity_policy.rb
- app/policies/user_response_policy.rb
- app/views/activities/show.html.erb
- config/routes.rb
- test/controllers/user_responses_controller_test.rb
- Created show action + show page for activities
- Created UserResponses controller with create action + added to policy
- Displayed user_response form on the activity show page for each activity_question
- Go to an activity, should see it's questions and a form to answer each one
- After saving an answer, check in the rails console that it was created.
NOTE: If you save an answer, whole page refreshes, so next to-do is to prevent page refresh + inline creation/editing
> Activities show page

- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
- Added links to navbar
- Added links to each student's profile in the classroom page
> Links everywhere

- Gemfile
- Gemfile.lock
- app/controllers/activities_controller.rb
- app/models/activity.rb
- app/views/activities/index.html.erb
- db/seeds.rb
- Using pg_search gem, added the search function for activities.
- For better testing, I added an activity to the seed called Theatre Match Game, with an activity type of Match.
To test:
- bundle install, rails db:seed
- On activity page, try to search multiple terms.
> Added the search function to the activities page using pg_search gem

- app/controllers/activities_controller.rb
- app/controllers/teacher_comments_controller.rb
- app/models/teacher_comment.rb
- app/policies/teacher_comment_policy.rb
- app/views/activities/results.html.erb
- app/views/profiles/show.html.erb
- config/routes.rb
- db/migrate/20221209162359_remove_activity_from_teacher_comment.rb
- db/migrate/20221209162731_remove_student_from_teacher_comment.rb
- db/migrate/20221209162859_add_user_response_to_teacher_comment.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/teacher_comments_controller_test.rb
- Changed TeacherComment model to be link to UserResponse
- Updated the sees accordingly
- Generated the controller for TeacherComments
- Did the policy for create?
- Did the route and action to create a TeachersComment ( the form will only appear if the user have a UserResponse for the Activity)
- Added link in the profile page to go to results if you are a teacher or current_user ( User are link to all activity because of the badge table, but some have no user response so the form wont appear)
To test rails db:migrate, rails db:seed ( you might have to drop the database), log in as as the teacher and try to go to a results page where there is UserResponse
> Teachers comment

- app/controllers/activities_controller.rb
- app/controllers/user_responses_controller.rb
- app/views/activities/results.html.erb
- app/views/activities/show.html.erb
- Moved the user_response form to the results page so a user can submit their answers and see them there directly.
- The user_response form is shown only to a student, not a teacher
- The user_response form is not shown to the student if they already answered this question
- Added name of teacher next to their comment + name of student at top of page
Left to do: add an edit link for the student's answer
> User responses added on the /results page

- app/controllers/user_responses_controller.rb
- app/javascript/controllers/edit_ajax_controller.js
- app/javascript/controllers/index.js
- app/policies/user_response_policy.rb
- app/views/activities/_user_responses_info.html.erb
- app/views/activities/results.html.erb
- config/routes.rb
- Created stimulus controller `edit_ajax_controller.js` to handle inline editing of a user_response
- Moved user_response display + edit form display to a partial `user_responses_info.html.erb`
- Sign in as a student and fill out an activity
- An edit button should be next to your responses + the "create" form should be gone
- Clicking on edit dynamically displays an edit form and after saving your new answer should be displayed
> Inline editing of user_responses

- app/controllers/pages_controller.rb
- app/javascript/controllers/index.js
- app/javascript/controllers/map_controller.js
- app/views/layouts/application.html.erb
- app/views/pages/play.html.erb
- package.json
- yarn.lock
- Implemented mapbox
- Created the stimulus Controller for map
- Display the map in the play page
- Display the marker on the play page ( hardcoded to theatre st-denis )
to test go on the play page to see the map, don't forget to yarn and add the key in env that I posted in the slack
> implemented mapbox on the play page

- app/models/badge.rb
Added below to Badge model:
```
enum status: {
unavailable: 0,
available: 1,
started: 2,
marked: 3,
completed: 4
}
```
> made badge's status column enum

- app/views/classrooms/show.html.erb
- db/migrate/20221213165523_add_date_to_classroom.rb
- db/schema.rb
- db/seeds.rb
- Added date to Classroom table
- Updated seed so classrooms have a date
- Modified the view of the classroom to display the date at the top
Test:
- Check the classroom to make sure the date is displayed
> Added date to Classroom, updated seed and view

- app/controllers/classrooms_controller.rb
- app/views/classrooms/show.html.erb
- db/seeds.rb
- Added code in classroom view to display student progress
- Modified seed to display different progress values
Test:
- Check classroom as student and teacher to see progress
> Student progress

- app/assets/stylesheets/components/_box.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/pages_controller.rb
- app/views/pages/play.html.erb
- Added css to the play page
- Tried to make it look like the figma
- The pictures are placeholder
- Updated the play info with the one they want to use
To do: Maybe make the map static, and add arrow to the photo scrollbox, fix the padding/margin and find color scheme
> Front end show page

- app/controllers/application_controller.rb
- app/views/devise/registrations/new.html.erb
- Added required params for classroom_id
- Added first and last name to sign up form
> Fix sign up

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
- Added blue/gray variables (same as Figma)
- Used Manrope as body & header font
- Changed navbar colors
> Font color variables

- app/assets/stylesheets/components/_badge.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_classroom.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/classrooms/show.html.erb
- app/views/shared/_navbar.html.erb
Attempted to style the classroom page per the Figma.
- Added badge component
- Added classroom css page
Left to do: 
- Currently blank for a student except for a blurb... not sure whether to show same page but with links to badges disabled? 
- Make names appear on one line
> Classroom page style

- app/assets/stylesheets/components/_blurb.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_activities.scss
- app/assets/stylesheets/pages/_classroom.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/activities/index.html.erb
Styled activities page per Figma
- Added blurb component
- Added activities.scss page
> Style activities page

- app/controllers/activities_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/profiles_controller.rb
- app/policies/profile_policy.rb
- app/views/pages/dashboard.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- db/migrate/20221214203408_add_admin_to_users.rb
- db/schema.rb
- db/seeds.rb
- Added a admin boolean to User
- Added routes, action, view to see a dashboard if you are an admin
- Added a custom method to toggle teacher boolean
- Added a admin to the seeds
- Added an admin classroom to the seed
to test log in as the admin (a@admin.com password: aaa111) and in the nav bar dropdown there should be a admin link
and then try to change student to teacher
left to do: style the page and prevent refresh behaviour on the page
> Implement admin

- app/controllers/activities_controller.rb
- app/controllers/application_controller.rb
- app/controllers/badges_controller.rb
- app/views/activities/index.html.erb
- app/views/activities/results.html.erb
- config/routes.rb
- test/controllers/badges_controller_test.rb
- Created badge Controller
- Did a before_action to find locked vs unlocked activities
- Now when we sign up it assign available only to level 1
- Display in activities the unlocked and locked one
- Did a custom routes and action so a teacher can mark an assignment as completed
to test log in as a teacher and go to a result page and change a student assignment to completed
> Unlock activity

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_question.scss
- app/assets/stylesheets/pages/_classroom.scss
- app/views/activities/_user_responses_info.html.erb
- app/views/activities/index.html.erb
- app/views/activities/results.html.erb
- app/views/activities/show.html.erb
- app/views/classrooms/show.html.erb
- Added question css component
- Styled the results page from the student vs teacher perspectives
> Style results page

- db/seeds.rb
- 2 classrooms, each with 1 teacher (2 total) and 8 students (16 total), all unique
- 8 activities:
- 3 quizes, each with 8 questions, levels 1 to 3
- 2 match games, with 4 questions, levels 2 and 3
- 2 art/color game, 1 question, level 2 and 3
- 1 review, 1 question, level 1
1 student has badges for 7 activities
- 5 badges completed, 1 reviewed, 1 started, 1 unavailable (review)
- - completed and reviewed have all answers completed, started have 4
2 students have badges for 5 activities
- 2 badges completed, 2 reviewed, 1 started, 1 available, 2 unavailable (review and quiz 3)
- - completed and reviewed have all answers completed, started have 4
4 students have badges for 3 activities
- 1 badge completed, 1 reviewed, 1 started, 2 available, 3 unavailable
- - completed and reviewed have …
> Modifying seed

- app/views/activities/results.html.erb
Small fix in CSS + adjusted condition in /results page to display the page's content if the user is a teacher
> Fixed results page logic for teacher

- app/views/activities/index.html.erb
- db/seeds.rb
- Added admin
- Fixed review activity association
- Fixed locked activities
> Added admin to seed, fixed review activity, fixed locked activities

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
- app/views/shared/_footer.html.erb
Added a footer, fixed it to the bottom
> added footer

- app/assets/stylesheets/components/_badge.scss
- app/controllers/classrooms_controller.rb
- app/views/classrooms/show.html.erb
- Set colours to badge statuses
- Badge colour appears accordingly in the classroom page
PS colours not too pretty right now, we can change to nicer ones
> added logic to set color of badge according to its status

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_home.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_profile.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/pages/play.html.erb
- Styled the profile page
- added link depending if you are teacher or not
- Fixed the margin on the profile page
-added a content wrap
theres still blah blah filler in the box since im not sure what to write there
> Style landing page

- app/controllers/application_controller.rb
- app/models/user.rb
- app/views/classrooms/show.html.erb
- app/views/devise/registrations/new.html.erb
- db/migrate/20221220194551_add_access_code_to_user.rb
- db/schema.rb
- db/seeds.rb
- Added `before_validation` action in user.rb that allows a teacher to sign up using the access_code "placeholderTC"
- A classroom is also created once a teacher signs up, and an access_code is added to that classroom.
- A student can then sign up using that classroom's access_code
- The classroom's access_code is displayed to the teacher on the classroom's show page as below: 
- Sign up as a teacher using the access_code "placeholderTC"
- Go to classroom page and copy the access_code
- Log out and sign in as a student by using the copied access_code
- Should have successfully created teacher & student accounts linked to the same classroom
> Access code signup

- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
- Added some how-to steps for a signed in user vs new user as per below
Signed in:
Signed out:
> Add how to use

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
**Small fix:** Made navbar sticky, made footer not sticky i.e. showing only when scrolled to bottom
> Navbar footer fix

- app/views/activities/_user_responses_info.html.erb
- app/views/activities/index.html.erb
- app/views/activities/results.html.erb
- db/seeds.rb
- Added the three activities to the seed
- Added badge for existing user
- added a elseif to the form to display multiple choice if choices array not empty on the create and edit form for user_response
- Added son class btn on a few Link-to
to test:
- rails db:migrate and try to fill in the pre show, general theater or post show activities
left to do:
- make post show unavailable until after the show.
- maybe add a column to activity for info about the activity because we only have a title for now
> Add 3 activities

- db/migrate/20221222175037_adding_description_to_activities.rb
- db/schema.rb
- db/seeds.rb
- Added a desription field to activities
- Changed text fields in several tables to text type instead of string
- Changes reflected in the seed
Test:
Run the migration and seed to make sure everything works. I didn't add a description in the view, so we won't be able to see it yet.
> Added description to activities, modified some fields to be text instead of string.

- app/controllers/classrooms_controller.rb
- db/seeds.rb
- Changed access code for seeded teacher, as it created a classroom and was no longer assigned to the seeded classroom
- Fixed classroom show action to only display the users classroom
Test:
Seed, and check the classroom show page. Try to make a few users as well.
> Fixed seed for classroom creation by teacher, users can only view their classroom

- app/assets/stylesheets/components/_box.scss
- app/models/badge.rb
- app/views/pages/home.html.erb
- app/views/pages/play.html.erb
- Added real show image/actor
-still need more image from the show, which i could not find. and direction to how to get to the 
play
> Adding real play img

- app/assets/stylesheets/pages/_activities.scss
- app/views/activities/show.html.erb
- db/seeds.rb
- Added descriptions to Pre Show and Post Show activities in the seeds
- Styled activity show page
- Removed 'Text' label from inputs on the results page
> Style activity show

- app/controllers/application_controller.rb
- app/controllers/classrooms_controller.rb
- app/models/badge.rb
- app/models/classroom.rb
- app/policies/classroom_policy.rb
- app/views/classrooms/settings.html.erb
- app/views/classrooms/show.html.erb
- config/routes.rb
- db/seeds.rb
- Started creating the settings page, action in the controller started.
- Fixed badge creation on user creation so that teachers don't get badges created
- Modified the seed so that users are associated with the proper classrooms and classrooms are created for teachers when their user is created
- Some things I made are commented out for now, since they were difficult to impliment.
Test:
Access the settings page.
> Teacher settings

- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
> added styling to signup and login pages

- app/controllers/activities_controller.rb
- app/controllers/classrooms_controller.rb
- app/views/activities/results.html.erb
- app/views/activities/show.html.erb
- db/seeds.rb
- Seed is only relevant data
- Unavailable methods on some pages caused errors, changed to active method
Test:
Run seed, check results page as teacher and student
> Seed only contains data related to the show, fixed results display with new migrations

- app/controllers/activities_controller.rb
- app/controllers/application_controller.rb
- app/controllers/classrooms_controller.rb
- app/views/activities/index.html.erb
- app/views/classrooms/settings.html.erb
- app/views/classrooms/show.html.erb
- config/routes.rb
- db/seeds.rb
- Addded add activity and remove activity from classroom
- sign_up change badges status depending on the classroom activities
- styled the setting page
- change activities index to display only choose activity
- change classroom show to display only choose activity.badge
to test: create a new teacher add activity to the classroom( the link button is on the classroom page), then create a student with the new classroom access code.
> adding activities now works

- app/controllers/application_controller.rb
- app/models/user.rb
- Moved create_badges from create application_controller.rb to user.rb
to test try to create user and see if you have badge, then try to create activity to see if it goes through
> now it work

- app/views/activities/show.html.erb
- teacher can now see activity descriptions
> teacher now see activity guideline

- app/controllers/badges_controller.rb
- app/controllers/profiles_controller.rb
- app/views/activities/results.html.erb
- app/views/profiles/show.html.erb
- config/routes.rb
- db/seeds.rb
- Created a route to change badge status to "marked"
- did the action in badges controller
- added a button to the results page
- we can now see in the profile page marked act
> we now have a button to display activity as marked on the result page

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_box.scss
- app/assets/stylesheets/components/_home.scss
- app/assets/stylesheets/components/_index.scss
- app/javascript/controllers/map_controller.js
- app/views/pages/home.html.erb
- app/views/pages/play.html.erb
- Fixed font size and background
- Adjusted image banner, though still not quite what was requested
- Map is no longer interactable
Test:
Try on multiple displays to make sure it presents well.
> Fixed text boxes so they're more readable, map doesn't move

- app/assets/stylesheets/components/_navbar.scss
- app/views/pages/play.html.erb
- app/views/shared/_navbar.html.erb
> Modified the navbar as requested

- app/models/user_response.rb
- app/views/activities/results.html.erb
- Teacher can only leave 1 comment for each response
- Student cannot submit an empty response
- Login as teacher & try adding a comment
- Login as a student & try saving response without entering anything
> Teacher comments student response

- app/controllers/teacher_comments_controller.rb
- app/javascript/controllers/edit_ajax_controller.js
- app/models/teacher_comment.rb
- app/policies/teacher_comment_policy.rb
- app/views/activities/_teacher_comments_info.html.erb
- app/views/activities/index.html.erb
- app/views/activities/results.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- db/seeds.rb
- Teacher can now edit or delete their comments
- Login as a teacher and leave a comment on a student's answer, the comment should be displayed with an "edit" and "delete button underneath.
- Click on edit, should be able to edit and save. 
- Click on delete, should be able to delete the comment.
> Teacher comment - edit & delete

- app/controllers/classrooms_controller.rb
- app/javascript/controllers/classroom_activity_controller.js
- app/javascript/controllers/edit_ajax_controller.js
- app/javascript/controllers/index.js
- app/views/classrooms/settings.html.erb
- Add/remove activity now prevent the refresh
- Clicking on a button change to the opposite one as well as the action method
to test :
-login as a teacher and try to change multiple time each button and take a look if theres not more than one of the same activity in a classroom
> change button action valu and class

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_tooltip.scss
- app/views/pages/play.html.erb
- Added class and css for tooltip hover
- Added dummy text for now for the hover effect
to test:
go on the performance page and hover over the actor image
> added a hover on actor image

- app/controllers/badges_controller.rb
- app/views/activities/_user_responses_info.html.erb
- app/views/activities/results.html.erb
- Once we click on "complete activity" we will see if our answer is correct
- Added code to the mark function that will only change the status to mark if all activity are filled
- Added a flash message if it's been save or not
to test: 
log in as a student and try to complete activity without filling all the questions first, then try with all questions filled ( mixed of bad and correct answer)
> we can now see the correction once we complete the activity

- app/views/activities/results.html.erb
- Correct answers are displayed in a quiz for teachers even before students complete it
- Sign in as a teacher, go to classroom and click on a quiz under a student - should be able to see the correct answers to each question
- Sign in as a student, open a quiz - should not see the correct answers (until after activity is complete)
> displayed correct answers on quiz for teachers

- app/controllers/badges_controller.rb
- app/javascript/controllers/edit_ajax_controller.js
- app/policies/badge_policy.rb
- app/views/activities/_user_responses_info.html.erb
- app/views/activities/index.html.erb
- app/views/activities/results.html.erb
- test/policies/badge_policy_test.rb
- Added a pundit policy for Badge
- now redirect to classroom when a teacher complete an activity
- A flash saying that the activity is completed appear at the bottom of the screen after redirect
- once aa teacher complete an activity, the student can't edit answer
- Added font awesome icon for the locked activities and remove the message saying when it will unlock once unlocked ( in the same branch because I forgot to create a new one oups haha)
to test the complete method log in as a teacher and try to mark an activity as complete
and see if the student can edit is answer after
to test the locked/unlocked change the date on the seed just to see or switch the < to > in line 45 and 49 in the display of the view
> now redirected to classroom with a flash message

- app/assets/stylesheets/components/_box.scss
- app/views/classrooms/settings.html.erb
- app/views/pages/play.html.erb
- Added dummy captions under rehearsal photos in the Performance page
- Added dummy info on how to get there in the Performance page
- Added info on adding/removing activities in the Classroom Settings page
> Small tweaks/captions

- app/assets/stylesheets/components/_button.scss
- app/views/classrooms/settings.html.erb
- app/views/classrooms/show.html.erb
- app/views/pages/home.html.erb
- app/views/pages/play.html.erb
- app/views/profiles/show.html.erb
- db/seeds.rb
- Back links on every page, to home, activities, and the classroom where necessary
- Some small styling fixes on the profile page and where ever I added links
- Added shadows on buttons
Test:
Go to every page as a student and teacher and click on all the links
> Back links everywhere, minor bugfixes and styling

- app/assets/stylesheets/pages/_classroom.scss
- app/views/classrooms/settings.html.erb
- Activity titles are links in the classroom settings page
Test:
Clink on the links in the settings page
> Fix: links in settings page to each of the actvities

- app/assets/stylesheets/components/_icons.scss
- app/assets/stylesheets/components/_index.scss
- app/javascript/application.js
- app/views/activities/_icon_activity.html.erb
- app/views/activities/results.html.erb
- db/seeds.rb
- Audio on Click activity complete
- Audio plays on click, icons highlight on hover
Test:
Migrate if necessary, seed, restart rails server.
Try the activity, mark as complete when done.
> Icons with audio

- app/views/activities/results.html.erb
- app/views/classrooms/show.html.erb
Badge text now wraps, fitting within badge div.
> made badge text wrap

- app/assets/javascript/icons.js
- app/assets/stylesheets/components/_icons.scss
- app/assets/stylesheets/components/_tooltip.scss
- app/javascript/application.js
- app/views/activities/_crossword_activity.html.erb
- app/views/activities/_icon_activity.html.erb
- app/views/activities/_multiple_pop_up.html.erb
- app/views/classrooms/show.html.erb
- config/initializers/assets.rb
- Disable link_to for unmarked or uncompleted activities
- Remove the enter the classroom button in the classroom
to test: 
as a teacher see if unmarked or uncompleted activities has a link_to
> Disable click uncompleted activity

- app/assets/stylesheets/components/_tooltip.scss
- app/views/activities/_crossword_activity.html.erb
- app/views/activities/_icon_activity.html.erb
- Added button to complete and back to activities to the crossword
- Added back to activities button to multiple pop up
- Added the tootip to the 3 combine icon
- Switch the script to assets and changed const element to var, now works without refresh
to test:
see if all button apeears, and try to see if the icons.play() works without refresh
> added the back to activity and the complete button to crossword

- app/assets/stylesheets/components/_badge.scss
- app/views/classrooms/show.html.erb
- app/views/profiles/show.html.erb
- Added number of comments on an activity on profile pages
- changed unless current_user.teacher? to @user.teacher?, otherwise teacher can never see the activities
to test:
as a teacher try to leave comments on activity, mark it as complete and go see on the profile page if it display the correct amount of comments
> added the number of comments you have on an activity on profiles pages

- app/views/activities/_audio_activity.html.erb
- app/views/activities/_crossword_activity.html.erb
- app/views/activities/_icon_activity.html.erb
- app/views/activities/_multiple_pop_up.html.erb
- app/views/activities/_video_quiz_activity.html.erb
- app/views/activities/show.html.erb
- db/seeds.rb
- Added activity descriptions to all activities
- Fixed margins & padding/basic styling for activities
- Icon activity -> added short instruction to clarify hover/click
- **Crossword** -> check if the page looks okay
> Styling updates

- app/assets/javascript/crossword.js
- You can now answer The crosswords with the form
to test: try to fill in all answers of the crossword
note: I kept the way to type in the case just in case, If we don't need it let's just comment it out
Left to do: Probably style a bit the page
> Input for crossword

- app/views/pages/home.html.erb
- Added custom filler message for teacher vs student on home page
- Made a box like the others on the box ( not sure if they wanted another design, tell me what you guys think)
to test:
- log in as a teacher and student and go on the home page
> added custom message for student vs teacher

- app/javascript/controllers/character_counter_controller.js
- app/javascript/controllers/index.js
- app/views/activities/_review_activity.html.erb
Added a word count for the essay/review activity. 
To test, go to the Pre Show Essay activity and type stuff in, word count should update.
> Word count

- app/javascript/controllers/signup_controller.js
- app/views/devise/registrations/new.html.erb
- If you click on next and the value are empty, it wont go to next frame
- validation for password can't be shorter than 6 character
- Alert if the password do not match
to test: try to sign up and click next without putting value in fields
left to do: now it doesnt check if classroom exist and if not it do not create the user ( but that seems complicated)
> wont go to next frame if empty

- app/assets/javascript/crossword.js
- app/views/activities/_crossword_activity.html.erb
- added an id to the complete button on crossword page
- Added an if statement to the crossword form submit so it doesnt trigger on the complete button
to test: 
-try to mark as complete the crossword
> crossword js interfered with complete button

- app/controllers/badges_controller.rb
- app/views/activities/_video_essay_activity.html.erb
- Added conditional to the mark method
to test:
-Try to fill in video review activity and multiple choices answer
> Fix save vid essay

- app/assets/javascript/crossword.js
- app/assets/javascript/icons.js
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_blurb.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_icons.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/pages/_activities.scss
- app/views/activities/_audio_activity.html.erb
- app/views/activities/_icon_activity.html.erb
- app/views/activities/index.html.erb
- app/views/activities/show.html.erb
- app/views/activities/teacher/_icon.html.erb
- app/views/classrooms/show.html.erb
- app/views/pages/home.html.erb
- app/views/pages/play.html.erb
- app/views/profiles/show.html.erb
- db/seeds.rb
- Fixed misc. typos on many pages.
- Styling fixes for several pages
- Button styling and color is consistent with navbar
Test:
Seed and do a click through looking for typos and styling errors that remain.
> Styling tooltips etc

- app/views/profiles/show.html.erb
- Added line to sort notifications on the profile page.
Test:
Complete some activities as a student and check your profile.
> Added line to sort notifications

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_legend.scss
- app/views/classrooms/show.html.erb
Added legend for badges in the classroom page.
To test sign in as a teacher and go to classroom. Let me know if you think the styling should change.
> added legend in the classroom page

- app/controllers/activities_controller.rb
- app/controllers/teacher_comments_controller.rb
- app/javascript/controllers/edit_ajax_controller.js
- app/models/teacher_comment.rb
- Change the create for teacher_comments, changed render to redirect
- Added commentInfo and commentEdit targets and revealEditForm method
- to test:
try to leave a blank comment, it should not crash and a notice should appear
try to edit an answer
> fixed the blank teacher comment

- app/assets/stylesheets/components/_profile.scss
- app/models/activity.rb
- app/views/profiles/show.html.erb
- Changed profile page divs into a table for better alignment.
- Added the # of comments left by a teacher, text is different when teacher vs student is logged in.
> changed profile divs to a table, added teacher comments left

- app/views/activities/index.html.erb
- db/seeds.rb
- Disable completed and marked activities
to test:
marked or complete an activity, it should be disable and a message saying either activity marked or activity completed should be displayed
> disable click on marked and completed activities

- app/assets/stylesheets/pages/_activities.scss
- app/views/activities/index.html.erb
- app/views/profiles/show.html.erb
- Made links on activity page blue.
- Added colour to activity status for students.
> Small fixes

- app/assets/javascript/submit.js
- app/controllers/badges_controller.rb
- app/javascript/controllers/edit_ajax_controller.js
- app/models/badge.rb
- app/policies/badge_policy.rb
- app/views/activities/_review_activity.html.erb
- app/views/activities/_user_responses_info.html.erb
- app/views/activities/_video_essay_activity.html.erb
- app/views/activities/_video_quiz_activity.html.erb
- app/views/profiles/show.html.erb
- config/initializers/assets.rb
- config/routes.rb
- db/seeds.rb
- Small syntax fixes
- Used JavaScript to click all submit buttons for quizes
- Removed edit buttons after questions have been answered
- Hid the save answer buttons
Test:
- Click through all the activities and make sure that you can save only if all questions are answered.
> Removed edit button from quizes, succesfully

- app/views/activities/_review_activity.html.erb
- app/views/activities/_video_quiz_activity.html.erb
- Changed the conditional so the button disappeared if badge status is completed OR marked
to test:
try to submit activities and see if the button disappear
> changed complete button so it would dissapeared once marked

- app/assets/stylesheets/components/_crossword.scss
- app/assets/stylesheets/pages/_activities.scss
- app/views/activities/_crossword_activity.html.erb
- app/views/activities/_photo_popup_activity.html.erb
- app/views/activities/index.html.erb
- Fixed the mobile responsiveness on a few pages
to test:
try to do a click trough in mobile to see
> Mobile responsiveness

- app/javascript/controllers/index.js
- app/javascript/controllers/regex_controller.js
- app/views/activities/_video_essay_activity.html.erb
- Added validations with JS to check for a valid Youtube link.
- If not, submit button is disabled and the red border/styling is added until a valid link is submitted.
> added validations with JS for the video input

- app/views/activities/teacher/_icon.html.erb
Should now be able to hear the audio for the icons when logged in as teacher.
> fixed icon audio as teacher

- app/views/activities/_video_essay_activity.html.erb
- app/views/profiles/show.html.erb
When logged in as teacher
- Your own profile page has no headers for activities
- Video Review -> aligned comment box with video
- Changed some wording on the profile page of students
> Teacher profile comments

- app/views/activities/_review_activity.html.erb
- app/views/activities/_video_essay_activity.html.erb
As a student
- Video essay activity button changed to  "submit"
- Review activity button changed to  "submit"
> changed complete to submit on video essay & review activity

- app/javascript/controllers/edit_ajax_controller.js
- Remove the edit button from the js
> removed the edit button from review js

- app/assets/stylesheets/components/_profile.scss
- app/helpers/application_helper.rb
- app/views/profiles/show.html.erb
- Added a way to see if its mobile or not in application_helper.rb
- Change the display of the profile if its mobile
to test:
try to go to profile on mobile
> Profile mobile

- app/assets/javascript/submit.js
- app/javascript/controllers/edit_ajax_controller.js
- Created a async function
- Created a delay var
- added a window.location.reload to reload the page
- Now theres a little await time between sending all form and triggering the submitted action
to test: 
try to do a multiple answer quiz, try to see if it work with all questions answer, and when missing answers
> Fix submit button
